In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns

# text processing libraries
import re #regular expressions, die wir später beim Processing brauchen
import string
import nltk

# Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

In [3]:
pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install openpyxl --upgrade

Requirement already satisfied: openpyxl in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [62]:
#Word2Vec, Glove mal vorkodieren mit Hinweis dass es darüber hinaus noch mehr gibt

In [63]:
pip install scipy==1.12

Requirement already satisfied: scipy==1.12 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (1.12.0)
Requirement already satisfied: numpy<1.29.0,>=1.22.4 in c:\users\kaya\appdata\local\anaconda3\lib\site-packages (from scipy==1.12) (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [64]:
#falls der vorhergehende Code nicht weiterhilft in Kombination mit diesem hier mal probieren
# der Herr hat soll das Problem in seinem GitHub gefixt haben

#pip install git+https://github.com/piskvorky/gensim.git

Word2Vec - start with Pre-Trained from Google

In [66]:
#Word2Vec herunterladen über NLTK, damit wir auf das Pre-Training zugreifen können
import nltk
nltk.download('word2vec_sample')

[nltk_data] Downloading package word2vec_sample to
[nltk_data]     C:\Users\Kaya\AppData\Roaming\nltk_data...
[nltk_data]   Package word2vec_sample is already up-to-date!

True

In [67]:
'''
NLTK includes a pre-trained model which is part of a model that is trained on 100 billion words from the Google News Dataset. 
The full model is from https://code.google.com/p/word2vec/ (about 3 GB).
'''

'''
Word2Vec is one of the most popular pretrained word embeddings developed by Google. 
Word2Vec is trained on the Google News dataset (about 100 billion words). 
It has several use cases such as Recommendation Engines, Knowledge Discovery, and also applied in the different Text Classification problems.
The architecture of Word2Vec is really simple. It’s a feed-forward neural network with just one hidden layer. 
Hence, it is sometimes referred to as a Shallow Neural Network architecture.
'''

#das hier ist die Pruned variante mit 40k Wörtern 
# https://www.nltk.org/howto/gensim.html

import gensim
from nltk.data import find
word2vec_sample = str(find('models/word2vec_sample/pruned.word2vec.txt'))
pre_w2v_model = gensim.models.KeyedVectors.load_word2vec_format(word2vec_sample, binary=False)

In [68]:
#Versionscheck
print(gensim.__version__)

4.3.2

In [69]:
#Embedding mit ca. 44k Semantischen Wortbeziehungen
len(pre_w2v_model.key_to_index)

43981

In [70]:
#Each word is represented in the space of 300 dimensions
len(pre_w2v_model['negotiation'])

300

In [71]:
pre_w2v_model.most_similar(positive=['negotiation'], topn = 3)

[('negotiations', 0.816856861114502),
 ('negotiating', 0.7531847953796387),
 ('bargaining', 0.6434565782546997)]

In [72]:
#Beispielhafter Vektor über 300 Dimensionen
pre_w2v_model["negotiation"]

array([ 0.00503933,  0.0736899 , -0.0289142 ,  0.0624547 ,  0.0555153 ,
       -0.00116173,  0.0282533 , -0.0617938 ,  0.0565066 ,  0.0799685 ,
       -0.105743  ,  0.0134658 , -0.0305665 ,  0.0114005 , -0.107065  ,
        0.0806294 ,  0.1183    ,  0.00462627,  0.0256097 , -0.0156963 ,
        0.00078481,  0.067081  ,  0.00380015,  0.0852556 ,  0.0328796 ,
        0.0591502 , -0.109709  , -0.073029  ,  0.00805467, -0.044941  ,
        0.00305665, -0.0213139 , -0.0421321 ,  0.0456018 ,  0.0859165 ,
        0.0627852 , -0.00082612,  0.00636113,  0.0684028 , -0.148041  ,
        0.041306  ,  0.0391581 , -0.0366797 ,  0.0156137 , -0.15465   ,
        0.0105743 ,  0.00328383,  0.0137962 , -0.136145  ,  0.0845947 ,
       -0.00850904, -0.00950039, -0.0489063 , -0.035358  , -0.016605  ,
        0.0342014 ,  0.0472541 ,  0.00570023,  0.0614634 ,  0.041306  ,
       -0.142754  ,  0.0555153 , -0.0290794 ,  0.1031    ,  0.0138788 ,
        0.0829425 ,  0.03321   ,  0.0345318 ,  0.027262  , -0.11037   ,
        0.0190834 ,  0.0274272 ,  0.0551848 , -0.0143745 , -0.0146223 ,
       -0.00326318,  0.00234412,  0.0259402 ,  0.0211487 ,  0.031723  ,
       -0.0168529 ,  0.00261261,  0.0123918 ,  0.0280881 ,  0.0252793 ,
       -0.0426278 ,  0.0247836 ,  0.0690637 ,  0.0667505 , -0.025775  ,
        0.0650983 , -0.0123092 , -0.0269315 ,  0.0462627 ,  0.0209835 ,
       -0.142754  ,  0.0299056 , -0.0627852 ,  0.0697246 , -0.0224705 ,
       -0.0565066 , -0.0561762 , -0.0313926 , -0.0201573 , -0.0209835 ,
        0.0145397 ,  0.00235444, -0.089221  ,  0.0157789 , -0.0203226 ,
       -0.0717073 ,  0.012144  ,  0.0137962 , -0.0568371 , -0.0266011 ,
        0.0991345 ,  0.0938473 , -0.0723682 ,  0.0971518 ,  0.00710464,
        0.0416365 , -0.0152006 ,  0.0214791 ,  0.112352  , -0.102439  ,
       -0.0432887 , -0.0859165 , -0.0251141 , -0.070055  ,  0.0614634 ,
        0.0918646 ,  0.0348623 , -0.0469236 , -0.00280881, -0.0394886 ,
        0.02214   , -0.0541935 , -0.0591502 , -0.0852556 ,  0.012557  ,
       -0.0237923 ,  0.0388277 , -0.09583   , -0.1183    ,  0.025775  ,
        0.0558457 , -0.0545239 ,  0.0145397 , -0.0122266 , -0.0305665 ,
        0.100456  , -0.00322187,  0.0865774 ,  0.0355232 , -0.0218096 ,
       -0.00213759,  0.0938473 , -0.079638  , -0.0465932 ,  0.0601416 ,
       -0.0802989 ,  0.0290794 , -0.0213139 , -0.0505586 , -0.0918646 ,
        0.0135484 ,  0.0371754 , -0.0166876 ,  0.0100374 ,  0.0489063 ,
       -0.00373819,  0.0141267 ,  0.0713768 , -0.0773249 ,  0.0912037 ,
       -0.0601416 ,  0.020653  , -0.00485346, -0.00357297, -0.0142093 ,
       -0.0492368 , -0.0378363 ,  0.0736899 ,  0.150684  ,  0.0535326 ,
        0.0153658 , -0.00245771,  0.0432887 ,  0.0647678 ,  0.00380015,
       -0.103761  ,  0.0340362 , -0.00460562,  0.0726986 ,  0.0713768 ,
       -0.0259402 , -0.0391581 ,  0.0190834 , -0.0502281 , -0.0335405 ,
        0.0446105 ,  0.0244532 ,  0.0300708 ,  0.0485759 ,  0.0111526 ,
       -0.0806294 , -0.0532022 , -0.0664201 ,  0.0495672 ,  0.0558457 ,
        0.0726986 , -0.105743  ,  0.00410995,  0.0144571 , -0.0388277 ,
        0.02214   ,  0.0690637 ,  0.0112352 ,  0.00149734,  0.0591502 ,
       -0.0153658 , -0.0541935 ,  0.00941777,  0.0634461 ,  0.111691  ,
        0.0452714 ,  0.11037   ,  0.0558457 ,  0.0134658 ,  0.0218096 ,
        0.09583   , -0.09583   , -0.0226357 ,  0.0872383 ,  0.0690637 ,
       -0.0109874 ,  0.00855035, -0.0152006 ,  0.130857  ,  0.0515499 ,
        0.0522108 , -0.0667505 , -0.0736899 , -0.039819  ,  0.0256097 ,
       -0.0624547 , -0.0137136 ,  0.0204052 ,  0.0598111 ,  0.0109048 ,
       -0.00623721,  0.047915  , -0.0905428 ,  0.0218096 ,  0.0075177 ,
        0.0378363 , -0.00499803, -0.0541935 ,  0.0472541 , -0.0190008 ,
        0.0432887 , -0.0836034 , -0.00817859, -0.00048793, -0.050889  ,
        0.057498  ,  0.0150354 , -0.0505586 , -0.146058  ,  0.0156963 ,
        0.0465932 ,  0.133501  ,  0.0836034 , -0.0429583 ,  0.00227183,
        0.0859165 , -0.0261054 ,  0.0885601 , -0.0269315 ,  0.0373406 ,
       -0.0964909 ,  0.0114005 ,  0.00846773,  0.0617938 ,  0.0878992 ,
        0.0004776 , -0.0505586 ,  0.1183    ,  0.0337057 , -0.00656766,
       -0.060472  ,  0.00677419,  0.0842643 ,  0.0323839 , -0.0393233 ,
        0.11764   , -0.044941  , -0.0416365 , -0.0654287 ,  0.0122266 ],
      dtype=float32)

In [73]:
pre_w2v_model.most_similar(positive=['disappointed'], topn = 5)

[('dismayed', 0.7374081611633301),
 ('surprised', 0.7143489718437195),
 ('displeased', 0.6827142238616943),
 ('saddened', 0.6556360125541687),
 ('pleased', 0.6533657312393188)]

In [74]:
#beim pre-trained w2vec keine Anwendung auf den zugrundeliegenden Textdaten notwendig
# diese werden erst bei der Modellierung zusammengeführt, Bsp. für LSTM:

'''
embedding_vectors = get_weight_matrix(w2v_model, word_index)
'''

'\nembedding_vectors = get_weight_matrix(w2v_model, word_index)\n'

Originales Word2Vec (nachfolgend) - nur zum Andiskutieren/nicht zeigen

In [76]:

'''
Pre-trained 300-dimensional vectors for about 3 million words and phrases, trained on a portion of the Google News dataset.

--> diese Version inkl. der nachfolgenden LOCs zuhause mal probieren, originales W2Vec ist nämlich zwischen 1,5gb und 3gb groß.
'''

#Download from Google or else: 
# https://www.kaggle.com/datasets/sugataghosh/google-word2vec?resource=download

'\nPre-trained 300-dimensional vectors for about 3 million words and phrases, trained on a portion of the Google News dataset.\n\n--> diese Version inkl. der nachfolgenden LOCs zuhause mal probieren, originales W2Vec ist nämlich zwischen 1,5gb und 3gb groß.\n'

In [77]:
#um das originale herunterzuladen das auskommentierte herunterladen und dann Schritte aus vorhergehenden anwenden
# im Kurs nicht durchführen, das dauert zu lange

'''
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
'''

"\nimport gensim.downloader as api\nwv = api.load('word2vec-google-news-300')\n"

In [78]:
# Hinweis, dass über t-sne auch visualisierbar
# Pre-trained hat natürlich den Bias, dass dieses nicht auf den Korpus zugeschnitten trainiert wurde, sondern generell auf Google-Beiträgen

Word2Vec - Self-Trained - hier weitercodieren

In [80]:
#Als Vorbereitung wollen wir in den nachfolgenden LOCs unseren Nego-Message_Daten erstmal vorbereiten:

In [81]:
#Was ist unsere Datenbasis? Wiederholung: 
df['Content']

ExperimentID
2020_12    dear mr williams happy responsible negotiation...
2020_12    dear mr brown pleased hear youthank last messa...
2020_12    dear mr williams thank quick cooperative respo...
2020_12    dear mr brown concessions last offer showed ri...
2020_12    dear mr williams thank much response happy fou...
                                 ...
2020_06    dear chis meyer thank latest offer points comp...
2020_06    dear alex kramerthank much latest offer happy ...
2020_06    dear chris meyerthank fast answer happy found ...
2020_06    dear alex krameri still interested coming join...
2020_06    dear chris meyer im sorry accept less mei unde...
Name: Content, Length: 1150, dtype: object

In [82]:
#Zwischenspeichern
nego_message_data = df['Content']
nego_message_data

ExperimentID
2020_12    dear mr williams happy responsible negotiation...
2020_12    dear mr brown pleased hear youthank last messa...
2020_12    dear mr williams thank quick cooperative respo...
2020_12    dear mr brown concessions last offer showed ri...
2020_12    dear mr williams thank much response happy fou...
                                 ...
2020_06    dear chis meyer thank latest offer points comp...
2020_06    dear alex kramerthank much latest offer happy ...
2020_06    dear chris meyerthank fast answer happy found ...
2020_06    dear alex krameri still interested coming join...
2020_06    dear chris meyer im sorry accept less mei unde...
Name: Content, Length: 1150, dtype: object

In [83]:
#df bauen
df_nego_message_data = pd.DataFrame(nego_message_data)
df_nego_message_data

                                                        Content
ExperimentID
2020_12       dear mr williams happy responsible negotiation...
2020_12       dear mr brown pleased hear youthank last messa...
2020_12       dear mr williams thank quick cooperative respo...
2020_12       dear mr brown concessions last offer showed ri...
2020_12       dear mr williams thank much response happy fou...
...                                                         ...
2020_06       dear chis meyer thank latest offer points comp...
2020_06       dear alex kramerthank much latest offer happy ...
2020_06       dear chris meyerthank fast answer happy found ...
2020_06       dear alex krameri still interested coming join...
2020_06       dear chris meyer im sorry accept less mei unde...

[1150 rows x 1 columns]

In [84]:
#Tokenisierung nochmal durchführen (jetzt mal einen anderen Weg ohne RegEx)
from nltk.tokenize import word_tokenize
nltk.download('punkt')

df_nego_message_data['Tokenized_Content'] = df_nego_message_data['Content'].apply(word_tokenize)
df_nego_message_data

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Kaya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,Content,Tokenized_Content
ExperimentID,,
2020_12,dear mr williams happy responsible negotiation...,"[dear, mr, williams, happy, responsible, negot..."
2020_12,dear mr brown pleased hear youthank last messa...,"[dear, mr, brown, pleased, hear, youthank, las..."
2020_12,dear mr williams thank quick cooperative respo...,"[dear, mr, williams, thank, quick, cooperative..."
2020_12,dear mr brown concessions last offer showed ri...,"[dear, mr, brown, concessions, last, offer, sh..."
2020_12,dear mr williams thank much response happy fou...,"[dear, mr, williams, thank, much, response, ha..."
...,...,...
2020_06,dear chis meyer thank latest offer points comp...,"[dear, chis, meyer, thank, latest, offer, poin..."
2020_06,dear alex kramerthank much latest offer happy ...,"[dear, alex, kramerthank, much, latest, offer,..."
2020_06,dear chris meyerthank fast answer happy found ...,"[dear, chris, meyerthank, fast, answer, happy,..."
2020_06,dear alex krameri still interested coming join...,"[dear, alex, krameri, still, interested, comin..."
2020_06,dear chris meyer im sorry accept less mei unde...,"[dear, chris, meyer, im, sorry, accept, less, ..."

In [85]:
# Das tokenisierte Format ist nun eine Liste Wörtern
sentences = df_nego_message_data['Tokenized_Content'].tolist()
sentences

[['dear',
  'mr',
  'williams',
  'happy',
  'responsible',
  'negotiation',
  'representative',
  'innovax',
  'settle',
  'last',
  'issuesyou',
  'certainly',
  'aware',
  'outbreak',
  'bse',
  'pandemic',
  'great',
  'concern',
  'association',
  'determined',
  'stop',
  'spread',
  'disease',
  'vaccination',
  'therefore',
  'looking',
  'come',
  'agreement',
  'strongly',
  'believe',
  'able',
  'reach',
  'agreement',
  'suits',
  'us',
  'communicate',
  'well',
  'therefore',
  'willing',
  'communicate',
  'openly',
  'regarding',
  'importance',
  'different',
  'issues',
  'delivery',
  'time',
  'one',
  'important',
  'issues',
  'us',
  'would',
  'like',
  'vaccine',
  'soon',
  'possible',
  'ideally',
  'month',
  'another',
  'important',
  'issue',
  'guarantee',
  'ideally',
  'agree',
  'full',
  'guarantee',
  'since',
  'need',
  'compensation',
  'damages',
  'occur',
  'moreover',
  'price',
  'another',
  'big',
  'concern',
  'would',
  'suggest',
  'price',
  'usd',
  'two',
  'issues',
  'certainly',
  'important',
  'well',
  'leave',
  'make',
  'suggestions',
  'values',
  'issues',
  'publicity',
  'future',
  'testing',
  'looking',
  'forward',
  'hearing',
  'feel',
  'issues',
  'work',
  'deal',
  'youwith',
  'best',
  'regards',
  'mr',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'pleased',
  'hear',
  'youthank',
  'last',
  'message',
  'unfortunately',
  'still',
  'open',
  'points',
  'can',
  'not',
  'accept',
  'renegotiatedin',
  'attachments',
  'find',
  'first',
  'offeri',
  'would',
  'aim',
  'best',
  'possible',
  'outcome',
  'us',
  'cooperation',
  'could',
  'stop',
  'spread',
  'disease',
  'therefore',
  'course',
  'willing',
  'negotiate',
  'certain',
  'points',
  'open',
  'communication',
  'comprehend',
  'point',
  'view',
  'situation',
  'need',
  'vaccination',
  'quickly',
  'innovax',
  'need',
  'months',
  'able',
  'produce',
  'requested',
  'amountconcerning',
  'guarantee',
  'open',
  'conceding',
  'wide',
  'guarantee',
  'good',
  'level',
  'guarantee',
  'price',
  'suggestion',
  'unfortunately',
  'unacceptable',
  'development',
  'vaccine',
  'expensive',
  'process',
  'make',
  'sure',
  'made',
  'best',
  'experts',
  'world',
  'longtime',
  'research',
  'also',
  'big',
  'concern',
  'suggest',
  'price',
  'usdfor',
  'last',
  'two',
  'issues',
  'suggest',
  'midterm',
  'maybe',
  'us',
  'interest',
  'therefore',
  'suggest',
  'narrow',
  'publicity',
  'standard',
  'level',
  'future',
  'testing',
  'id',
  'like',
  'hear',
  'point',
  'view',
  'argumentation',
  'kind',
  'regardsmr',
  'williams'],
 ['dear',
  'mr',
  'williams',
  'thank',
  'quick',
  'cooperative',
  'response',
  'see',
  'certain',
  'issues',
  'discuss',
  'order',
  'find',
  'suitable',
  'solution',
  'interests',
  'following',
  'come',
  'back',
  'valid',
  'points',
  'regarding',
  'delivery',
  'time',
  'understand',
  'need',
  'time',
  'produce',
  'requested',
  'amount',
  'accept',
  'months',
  'however',
  'unfortunately',
  'precise',
  'enough',
  'us',
  'accept',
  'would',
  'innovax',
  'able',
  'deliver',
  'request',
  'delivery',
  'time',
  'months',
  'concerning',
  'guarantee',
  'accept',
  'offer',
  'regarding',
  'wide',
  'guarantee',
  'hope',
  'vaccine',
  'show',
  'promised',
  'effectiveness',
  'proposed',
  'price',
  'big',
  'concern',
  'able',
  'pay',
  'usd',
  'per',
  'dosis',
  'offer',
  'usd',
  'eyes',
  'good',
  'justified',
  'prize',
  'lets',
  'forget',
  'vaccine',
  'tested',
  'outside',
  'lab',
  'therefore',
  'can',
  'not',
  'fully',
  'judge',
  'effectiveness',
  'quality',
  'know',
  'regarding',
  'prize',
  'delivery',
  'time',
  'ask',
  'alot',
  'regarding',
  'future',
  'testing',
  'comfortable',
  'standard',
  'option',
  'accept',
  'offer',
  'even',
  'though',
  'possibility',
  'publicity',
  'surrounding',
  'topic',
  'would',
  'extremly',
  'bad',
  'company',
  'accept',
  'narrowpublicity',
  'hoping',
  'rethink',
  'first',
  'offer',
  'regarding',
  'prize',
  'delivery',
  'time',
  'looking',
  'forward',
  'hearing',
  'send',
  'best',
  'regards',
  'mr',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'concessions',
  'last',
  'offer',
  'showed',
  'right',
  'way',
  'successful',
  'agreement',
  'also',
  'want',
  'show',
  'goodwill',
  'therefore',
  'see',
  'accommodations',
  'offer',
  'appreciate',
  'concession',
  'regarding',
  'guaranteei',
  'think',
  'also',
  'already',
  'reach',
  'agreement',
  'publicity',
  'future',
  'testing',
  'focus',
  'attention',
  'issues',
  'delivery',
  'time',
  'pricefor',
  'us',
  'better',
  'delivery',
  'time',
  'could',
  'long',
  'possible',
  'least',
  'months',
  'make',
  'exception',
  'concede',
  'months',
  'price',
  'case',
  'usd',
  'pay',
  'investors',
  'expert',
  'employees',
  'researching',
  'decade',
  'value',
  'work',
  'hope',
  'understand',
  'accept',
  'offer',
  'wish',
  'nice',
  'day',
  'best',
  'regardsmr',
  'williams'],
 ['dear',
  'mr',
  'williams',
  'thank',
  'much',
  'response',
  'happy',
  'found',
  'agreement',
  'publicity',
  'future',
  'testing',
  'happy',
  'progress',
  'see',
  'fair',
  'possibility',
  'future',
  'cooperation',
  'price',
  'see',
  'points',
  'can',
  'not',
  'circumstances',
  'pay',
  'offered',
  'usd',
  'moment',
  'whilst',
  'admiting',
  'months',
  'delivery',
  'time',
  'however',
  'company',
  'would',
  'able',
  'provide',
  'months',
  'delivery',
  'time',
  'would',
  'willing',
  'pay',
  'use',
  'per',
  'dosis',
  'looking',
  'forward',
  'hearing',
  'thoughts',
  'finishing',
  'negotiation',
  'good',
  'outcome',
  'firms',
  'best',
  'regards',
  'mr',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'last',
  'offer',
  'great',
  'improvement',
  'hope',
  'bring',
  'negotiation',
  'pleasant',
  'result',
  'us',
  'us',
  'able',
  'provide',
  'vaccine',
  'months',
  'cost',
  'us',
  'therefore',
  'willing',
  'reach',
  'deadline',
  'provide',
  'doses',
  'usd',
  'hope',
  'could',
  'able',
  'pay',
  'price',
  'looking',
  'forward',
  'answer',
  'best',
  'wishes',
  'family',
  'mr',
  'williams'],
 ['dear',
  'mr',
  'williams',
  'thank',
  'pleasant',
  'negotiation',
  'cooperativeness',
  'even',
  'though',
  'usd',
  'high',
  'asking',
  'prize',
  'accept',
  'higher',
  'price',
  'means',
  'move',
  'faster',
  'urgent',
  'situation',
  'lets',
  'hope',
  'vaccine',
  'promised',
  'effect',
  'move',
  'crisis',
  'best',
  'regards',
  'merry',
  'christmas',
  'family',
  'mr',
  'brown'],
 ['dear',
  'innovax',
  'team',
  'first',
  'would',
  'like',
  'thank',
  'good',
  'cooperation',
  'past',
  'fortunately',
  'already',
  'reached',
  'agreement',
  'two',
  'negotiating',
  'points',
  'sure',
  'also',
  'find',
  'good',
  'agreement',
  'us',
  'remaining',
  'points',
  'outstanding',
  'points',
  'still',
  'need',
  'reach',
  'agreement',
  'follows',
  'delivery',
  'time',
  'vaccine',
  'price',
  'per',
  'dose',
  'guarantee',
  'vaccine',
  'effective',
  'cooperation',
  'future',
  'public',
  'relationspress',
  'releases',
  'looking',
  'forward',
  'receiving',
  'answer',
  'end',
  'side',
  'best',
  'regards',
  'michael',
  'brown'],
 ['dear',
  'michael',
  'brown',
  'nice',
  'meet',
  'always',
  'pleasure',
  'negotiate',
  'however',
  'points',
  'exceed',
  'sales',
  'limits',
  'would',
  'like',
  'make',
  'counteroffer',
  'price',
  'suggested',
  'cover',
  'expenses',
  'product',
  'would',
  'like',
  'suggest',
  'option',
  'im',
  'sure',
  'find',
  'options',
  'favorable',
  'best',
  'regards',
  'williams'],
 ['dear',
  'mr',
  'williams',
  'pleased',
  'hear',
  'sure',
  'understand',
  'economic',
  'action',
  'course',
  'must',
  'view',
  'fact',
  'current',
  'bse',
  'situation',
  'acute',
  'vaccine',
  'better',
  'used',
  'sooner',
  'rather',
  'later',
  'sure',
  'accommodate',
  'terms',
  'price',
  'return',
  'however',
  'faster',
  'delivery',
  'time',
  'essential',
  'us',
  'opinion',
  'regard',
  'would',
  'aim',
  'best',
  'possible',
  'outcome',
  'us',
  'therefore',
  'course',
  'willing',
  'negotiate',
  'points',
  'looking',
  'forward',
  'answer',
  'best',
  'wishes',
  'brown'],
 ['dear',
  'mrs',
  'brown',
  'im',
  'pleased',
  'get',
  'answer',
  'understand',
  'point',
  'regarding',
  'delivery',
  'time',
  'however',
  'complicated',
  'us',
  'carry',
  'delivery',
  'period',
  'suggested',
  'due',
  'amount',
  'tests',
  'need',
  'ensure',
  'safety',
  'suggest',
  'delivery',
  'period',
  'months',
  'also',
  'flexible',
  'guarantee',
  'publicity',
  'look',
  'forward',
  'hearing',
  'feedback',
  'want',
  'emphasize',
  'open',
  'negotiations',
  'best',
  'wishes',
  'williams'],
 ['dear',
  'mr',
  'wiliams',
  'please',
  'excuse',
  'delayed',
  'response',
  'first',
  'would',
  'like',
  'thank',
  'concession',
  'understand',
  'course',
  'safety',
  'vaccine',
  'guarantee',
  'comes',
  'essential',
  'element',
  'also',
  'reputation',
  'bse',
  'present',
  'moment',
  'want',
  'avoid',
  'infecting',
  'cows',
  'costs',
  'early',
  'delivery',
  'would',
  'enormous',
  'importance',
  'us',
  'sure',
  'accommodate',
  'terms',
  'price',
  'delivery',
  'time',
  'months',
  'would',
  'acceptable',
  'us',
  'could',
  'bridge',
  'time',
  'caution',
  'enourmous',
  'importance',
  'publicity',
  'mentioned',
  'beforehand',
  'really',
  'appreciate',
  'flexible',
  'view',
  'concerning',
  'future',
  'testing',
  'look',
  'forward',
  'continued',
  'cooperation',
  'future',
  'open',
  'new',
  'ideas',
  'best',
  'regards',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'would',
  'like',
  'thank',
  'cooperation',
  'dialogue',
  'view',
  'long',
  'professional',
  'relationship',
  'would',
  'like',
  'emphasize',
  'agree',
  'offer',
  'points',
  'guarantee',
  'publicity',
  'future',
  'testing',
  'since',
  'crucial',
  'points',
  'sure',
  'also',
  'find',
  'good',
  'agreement',
  'us',
  'remaining',
  'points',
  'best',
  'regards',
  'williams'],
 ['dear',
  'mr',
  'wiliams',
  'thank',
  'last',
  'message',
  'last',
  'message',
  'made',
  'concessions',
  'im',
  'willing',
  'consideration',
  'would',
  'like',
  'accept',
  'offered',
  'price',
  'could',
  'meet',
  'delivery',
  'time',
  'months',
  'eagerly',
  'awaiting',
  'answer',
  'hope',
  'deal',
  'point',
  'best',
  'wishes',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'would',
  'like',
  'thank',
  'cooperation',
  'throughout',
  'negotiation',
  'process',
  'happy',
  'inform',
  'accept',
  'offer',
  'hope',
  'continue',
  'make',
  'deals',
  'future',
  'best',
  'regards',
  'williams'],
 ['dear',
  'mr',
  'williams',
  'one',
  'executives',
  'nca',
  'going',
  'negotiation',
  'partner',
  'know',
  'still',
  'five',
  'issues',
  'negotiate',
  'attached',
  'find',
  'opening',
  'offer',
  'first',
  'step',
  'course',
  'certain',
  'issues',
  'need',
  'negotiate',
  'us',
  'important',
  'delivery',
  'time',
  'willing',
  'make',
  'concessions',
  'issues',
  'looking',
  'forward',
  'reply',
  'starting',
  'negotiation',
  'kind',
  'regards',
  'brown'],
 ['dear',
  'mr',
  'browni',
  'one',
  'executives',
  'innovax',
  'pleased',
  'hear',
  'attachments',
  'find',
  'first',
  'offer',
  'really',
  'need',
  'adjust',
  'concessions',
  'regarding',
  'delivery',
  'time',
  'also',
  'critical',
  'issue',
  'company',
  'discussing',
  'innovative',
  'product',
  'requires',
  'cutting',
  'edge',
  'technology',
  'order',
  'become',
  'able',
  'large',
  'scale',
  'production',
  'need',
  'extend',
  'deadline',
  'corcening',
  'guarantee',
  'cant',
  'afford',
  'full',
  'one',
  'sure',
  'product',
  'effectiveness',
  'nca',
  'innovax',
  'still',
  'dealing',
  'prominent',
  'risks',
  'fair',
  'share',
  'would',
  'aim',
  'best',
  'possible',
  'outcome',
  'us',
  'therefore',
  'course',
  'willing',
  'negotiate',
  'certain',
  'pointswith',
  'best',
  'regardswilliams'],
 ['dear',
  'mr',
  'williams',
  'thank',
  'first',
  'offer',
  'think',
  'already',
  'issues',
  'agree',
  'future',
  'testing',
  'fine',
  'publicity',
  'narrow',
  'also',
  'okay',
  'deicide',
  'gurantee',
  'wide',
  'would',
  'okay',
  'making',
  'concession',
  'would',
  'appreciate',
  'slightly',
  'faster',
  'delivery',
  'time',
  'understand',
  'isnt',
  'easy',
  'first',
  'offer',
  'month',
  'little',
  'fast',
  'manage',
  'need',
  'soon',
  'possible',
  'think',
  'new',
  'request',
  'even',
  'willing',
  'pay',
  'delivery',
  'time',
  'okay',
  'see',
  'offer',
  'attached',
  'course',
  'also',
  'interested',
  'best',
  'outcome',
  'us',
  'therefore',
  'well',
  'willing',
  'negotitate',
  'certain',
  'points',
  'think',
  'good',
  'way',
  'kind',
  'regards',
  'brown'],
 ['dear',
  'mr',
  'brown',
  'consideration',
  'delighted',
  'inform',
  'accept',
  'last',
  'offer',
  'got',
  'deal',
  'delivery',
  'time',
  'months',
  'demands',
  'strongly',
  'narrow',
  'schedule',
  'manage',
  'price',
  'requested',
  'contact',
  'suppliers',
  'pd',
  'team',
  'soon',
  'possible',
  'meet',
  'deadline',
  'honor',
  'negotiating',
  'point',
  'view',
  'weve',
  'reached',
  'common',
  'solution',
  'suits',
  'us',
  'best',
  'regards',
  'williams'],
 ['hello',
  'mr',
  'williams',
  'would',
  'like',
  'negotiate',
  'open',
  'points',
  'product',
  'going',
  'provide',
  'us',
  'allready',
  'agreed',
  'innovax',
  'provide',
  'vaccine',
  'cows',
  'herd',
  'furthermore',
  'terms',
  'payment',
  'days',
  'meets',
  'standard',
  'transactions',
  'currently',
  'following',
  'open',
  'points',
  'delivery',
  'time',
  'vaccine',
  'guarantees',
  'innovax',
  'vaccine',
  'effective',
  'side',
  'effects',
  'price',
  'vaccine',
  'per',
  'dose',
  'cow',
  'needs',
  'one',
  'dose',
  'publicity',
  'whether',
  'information',
  'test',
  'takes',
  'place',
  'possible',
  'details',
  'released',
  'public',
  'whether',
  'nca',
  'allow',
  'innovax',
  'testing',
  'vaccines',
  'cows',
  'please',
  'find',
  'attached',
  'first',
  'request',
  'hope',
  'hear',
  'back',
  'soon',
  'kind',
  'regards',
  'brown'],
 ['hi',
  'williams',
  'thank',
  'kind',
  'message',
  'prepared',
  'first',
  'offer',
  'according',
  'key',
  'points',
  'mentioned',
  'mail',
  'attachments',
  'find',
  'suggestion',
  'find',
  'agree',
  'price',
  'would',
  'want',
  'renegotiate',
  'terms',
  'delivery',
  'time',
  'would',
  'willing',
  'make',
  'concessions',
  'regarding',
  'future',
  'testing',
  'kind',
  'regards',
  'brown'],
 ['dear',
  'brownthanks',
  'offer',
  'unfortunately',
  'can',
  'not',
  'agree',
  'claims',
  'issue',
  'price',
  'reduction',
  'utility',
  'good',
  'cooperation',
  'since',
  'comprehend',
  'point',
  'view',
  'situation',
  'agree',
  'concede',
  'issuesif',
  'agree',
  'guarantee',
  'type',
  'narrow',
  'delivery',
  'time',
  'months',
  'willing',
  'concede',
  'issue',
  'publicity',
  'future',
  'testing',
  'wish',
  'nice',
  'daywith',
  'best',
  'regards',
  'william'],
 ['dear',
  'williams',
  'last',
  'message',
  'made',
  'interesting',
  'concessions',
  'im',
  'willing',
  'pleased',
  'offering',
  'concerning',
  'publicity',
  'need',
  'kindly',
  'ask',
  'make',
  'concessions',
  'regarding',
  'delivery',
  'time',
  'guarantee',
  'situation',
  'urgent',
  'sign',
  'cooperativeness',
  'would',
  'willing',
  'accept',
  'future',
  'testing',
  'unlimited',
  'higher',
  'price',
  'looking',
  'forward',
  'hearing',
  'soon',
  'kind',
  'regards',
  'brown'],
 ['dear',
  'brown',
  'still',
  'interested',
  'coming',
  'joint',
  'result',
  'appreciate',
  'latest',
  'offer',
  'much',
  'would',
  'fine',
  'months',
  'issue',
  'delivery',
  'time',
  'issues',
  'agree',
  'consideresi',
  'eagerly',
  'awaiting',
  'answer',
  'best',
  'regardswilliams'],
 ['dear',
  'williams',
  'thank',
  'much',
  'last',
  'offer',
  'consideration',
  'delighted',
  'inform',
  'accept',
  'point',
  'view',
  'weve',
  'reached',
  'common',
  'solution',
  'suits',
  'us',
  'really',
  'enjoyed',
  'negotiating',
  'kind',
  'regards',
  'stay',
  'healthy',
  'brown'],
 ['dear',
  'williams',
  'brown',
  'negotiation',
  'partner',
  'behalf',
  'nca',
  'already',
  'agreeing',
  'two',
  'seven',
  'issues',
  'previous',
  'talks',
  'confident',
  'able',
  'build',
  'success',
  'find',
  'pleasent',
  'solution',
  'us',
  'regarding',
  'remaining',
  'five',
  'issues',
  'terms',
  'first',
  'offer',
  'behalf',
  'nca',
  'following',
  'delivery',
  'time',
  'month',
  'price',
  'guarantee',
  'full',
  'publicity',
  'none',
  'future',
  'testing',
  'none',
  'hope',
  'offer',
  'satisfaction',
  'course',
  'always',
  'room',
  'negotiation',
  'looking',
  'forward',
  'hearing',
  'back',
  'soon',
  'best',
  'regards',
  'brown'],
 ['dear',
  'brown',
  'quite',
  'sure',
  'aware',
  'problem',
  'facing',
  'complex',
  'healthy',
  'problem',
  'science',
  'work',
  'values',
  'outrageous',
  'us',
  'order',
  'offer',
  'good',
  'efficient',
  'vaccine',
  'avoid',
  'disease',
  'spreading',
  'need',
  'collaborate',
  'deals',
  'properly',
  'according',
  'needs',
  'still',
  'know',
  'impacts',
  'avoiding',
  'animal',
  'diseases',
  'contact',
  'humans',
  'first',
  'delivery',
  'time',
  'months',
  'possible',
  'since',
  'working',
  'limited',
  'resources',
  'need',
  'best',
  'scientists',
  'field',
  'working',
  'fully',
  'achieve',
  'good',
  'product',
  'can',
  'not',
  'work',
  'price',
  'vaccine',
  'would',
  'offer',
  'hand',
  'work',
  'hard',
  'delivery',
  'within',
  'months',
  'remember',
  'vaccine',
  'taking',
  'ready',
  'regarding',
  'guarantee',
  'can',
  'not',
  'assure',
  'full',
  'scenario',
  'put',
  'real',
  'sight',
  'vaccines',
  'ready',
  'years',
  'testing',
  'first',
  'trial',
  'formula',
  'need',
  'understand',
  'might',
  'work',
  'narrow',
  'guarantee',
  'consider',
  'future',
  'testing',
  'publicity',
  'offered',
  'compensation',
  'well',
  'hope',
  'understand',
  'conditions',
  'offer',
  'fair',
  'negotiation',
  'matters',
  'kind',
  'regards',
  'jamie'],
 ['dear',
  'williams',
  'thank',
  'quick',
  'reply',
  'counteroffer',
  'think',
  'good',
  'first',
  'step',
  'quite',
  'points',
  'discuss',
  'side',
  'see',
  'challenging',
  'situation',
  'nevertheless',
  'firm',
  'quite',
  'distress',
  'well',
  'take',
  'outbreak',
  'bse',
  'seriously',
  'said',
  'highly',
  'value',
  'potential',
  'collaboration',
  'hope',
  'agree',
  'equally',
  'beneficial',
  'terms',
  'order',
  'express',
  'make',
  'concessions',
  'regarding',
  'issue',
  'price',
  'offer',
  'also',
  'extend',
  'publicity',
  'narrow',
  'well',
  'issue',
  'future',
  'testing',
  'unlimited',
  'high',
  'time',
  'pressure',
  'facing',
  'terms',
  'protecting',
  'herds',
  'fastspreading',
  'bse',
  'outbreak',
  'litulia',
  'thus',
  'regarding',
  'issue',
  'delivery',
  'time',
  'unfortunately',
  'insist',
  'month',
  'goes',
  'guarantee',
  'full',
  'hope',
  'understand',
  'situation',
  'looking',
  'forward',
  'reply',
  'best',
  'regards',
  'brown'],
 ['hello',
  'mr',
  'brown',
  'first',
  'sorry',
  'delay',
  'answer',
  'problems',
  'involving',
  'laboratory',
  'tests',
  'vaccines',
  'definitely',
  'world',
  'full',
  'technical',
  'inconveniences',

In [86]:
# vor Präsentation einmal durchgehen was das bedeutet
'''
The parameters of the following Word2Vec model:
    min_count = int - Ignores all words with total absolute frequency lower than this - (2, 100)
    window = int - The maximum distance between the current and predicted word within a sentence. E.g. window words on the left and window words on the left of our target - (2, 10)
    vector_size = int - Dimensionality of the feature vectors. - (50, 300)
    sample = float - The threshold for configuring which higher-frequency words are randomly downsampled. Highly influencial. - (0, 1e-5)
    alpha = float - The initial learning rate - (0.01, 0.05)
    min_alpha = float - Learning rate will linearly drop to min_alpha as training progresses. To set it: alpha - (min_alpha * epochs) ~ 0.00
    negative = int - If > 0, negative sampling will be used, the int for negative specifies how many "noise words" should be drown. If set to 0, no negative sampling is used. - (5, 20)
    workers = int - Use these many worker threads to train the model (=faster training with multicore machines)
'''

'\nThe parameters of the following Word2Vec model:\n    min_count = int - Ignores all words with total absolute frequency lower than this - (2, 100)\n    window = int - The maximum distance between the current and predicted word within a sentence. E.g. window words on the left and window words on the left of our target - (2, 10)\n    vector_size = int - Dimensionality of the feature vectors. - (50, 300)\n    sample = float - The threshold for configuring which higher-frequency words are randomly downsampled. Highly influencial. - (0, 1e-5)\n    alpha = float - The initial learning rate - (0.01, 0.05)\n    min_alpha = float - Learning rate will linearly drop to min_alpha as training progresses. To set it: alpha - (min_alpha * epochs) ~ 0.00\n    negative = int - If > 0, negative sampling will be used, the int for negative specifies how many "noise words" should be drown. If set to 0, no negative sampling is used. - (5, 20)\n    workers = int - Use these many worker threads to train the model (=faster training with multicore machines)\n'

In [87]:
# Word2Vec-Modell trainieren
# Parameter: Größe des Vektorraums, Mindestanzahl an Vorkommen für Wörter, Anzahl der Arbeits-Threads
from gensim.models.word2vec import Word2Vec

ourfirst_w2v_model = Word2Vec(sentences, vector_size=300, window=5, min_count=1, workers=4)
ourfirst_w2v_model.save("ourfirst_selftrained_w2v.model")
ourfirst_w2v_model

In [88]:
#siehe lokaler Datenspeicher, dass es gespeichert wurde im .model-Format

In [89]:
#kann später geladen werden
'''
model = Word2Vec.load("ourfirst_selftrained_w2v.model")
'''

'\nmodel = Word2Vec.load("ourfirst_selftrained_w2v.model")\n'

In [90]:
# Modell ist jetzt trainiert. Beispiel: Vektor für ein Wort erhalten

example_word_vector = ourfirst_w2v_model.wv['accept']
print("Vektor für das Wort: accept \n", example_word_vector)

Vektor für das Wort: accept
 [ 6.69419160e-03  2.24723980e-01  1.97072420e-02  1.32324591e-01
  1.80251449e-02 -2.78460830e-01  3.94661903e-01  8.56046557e-01
 -1.50145069e-02 -3.06172609e-01  1.42885745e-01 -1.34691179e-01
 -6.45972788e-02 -7.23459348e-02 -4.06471521e-01 -2.63426155e-01
  1.63233891e-01  1.95203856e-01  9.28171203e-02  8.14344808e-02
 -1.27669811e-01 -1.11502238e-01  4.22936827e-01  3.97451557e-02
  3.90967965e-01 -1.17787734e-01 -2.55228162e-01 -1.45603597e-01
 -3.52427624e-02 -2.25183696e-01 -2.22367153e-01 -1.78591520e-01
  2.49319360e-01 -2.70193666e-01  4.73094210e-02  2.60005504e-01
  9.13915113e-02 -4.33413237e-01 -4.35820296e-02 -9.76648405e-02
 -1.73997194e-01  1.79628566e-01  6.38162121e-02 -2.05948204e-01
  4.43648770e-02  1.57511726e-01  2.76308447e-01 -1.76455211e-02
 -8.76522064e-02  2.52060622e-01  3.96181941e-01 -1.02335282e-01
 -3.36443603e-01  7.40128988e-03 -1.98292211e-01  2.82093227e-01
  2.51496226e-01  8.02344456e-02  3.19666713e-01 -1.74698621e-01
 -2.51059622e-01  2.89008707e-01 -3.02234180e-02  1.68269455e-01
 -8.50180071e-03  3.32672775e-01  2.80051995e-02  1.52325809e-01
 -3.43300939e-01 -2.24173114e-01 -1.05816707e-01  2.83299863e-01
  6.21552408e-01 -4.53687400e-01 -9.35606807e-02  3.00034434e-02
 -7.51386359e-02  7.16218539e-03 -1.33289650e-01  6.10789537e-01
 -9.82613489e-02 -1.48584083e-01 -6.26466200e-02  6.01927102e-01
  2.32388139e-01 -1.24783941e-01 -9.91022438e-02  6.51129112e-02
  2.67252058e-01  6.62273541e-02  4.39118356e-01 -1.57660693e-01
  8.96929875e-02  8.74605477e-02  5.97932637e-01  1.42132178e-01
  2.80292511e-01 -4.20737356e-01 -8.23800042e-02  1.55173942e-01
 -1.49445832e-01  1.88573062e-01  1.00128636e-01  2.54706353e-01
  7.83589557e-02 -3.32146972e-01 -1.11219324e-01  1.09753266e-01
 -5.49494803e-01  3.07895601e-01 -3.01327497e-01 -3.00734006e-02
  1.16789483e-01  1.84602559e-01  2.96394490e-02  1.38716593e-01
 -9.40547604e-03  2.81426668e-01  4.69901055e-01 -3.27897519e-01
 -8.69295225e-02  1.66060150e-01  1.44716293e-01 -8.09554309e-02
 -2.95798272e-01  3.11943650e-01 -4.19367924e-02 -2.37301782e-01
 -6.03731759e-02  2.65379250e-01  1.66714862e-01  1.66512385e-01
  5.08024450e-03 -1.56183288e-01 -5.18847294e-02  1.11076765e-01
 -2.10844263e-01 -2.45147824e-01 -3.67523402e-01 -4.28267449e-01
  1.10871293e-01 -3.33150268e-01  2.62362272e-01  2.91417480e-01
  1.84454739e-01 -3.62823606e-01 -8.76987278e-02 -3.13459516e-01
  1.96583457e-02 -1.76380202e-01  2.88840413e-01 -7.53569722e-01
 -5.44937432e-01 -1.15611993e-01  2.24473834e-01  2.45439649e-01
 -1.56542167e-01 -2.65596479e-01  4.39677294e-03  3.17709893e-01
  1.18553825e-01  3.00979495e-01 -4.63437617e-01  3.96252424e-01
 -2.51564205e-01  1.44219428e-01  5.44640189e-03 -1.16399057e-01
 -5.28038181e-02  4.11235929e-01 -2.95672864e-01  3.18307765e-02
  7.54577368e-02  8.35658163e-02 -3.50213982e-02  3.17976087e-01
 -1.84290200e-01 -4.54528630e-02 -1.18512511e-02 -1.13626249e-01
 -5.02760075e-02  3.58080328e-01  7.10364282e-02  3.66983786e-02
 -3.33323106e-02  1.42241895e-01  3.13895851e-01  3.52359504e-01
  3.23665947e-01 -3.98997486e-01  2.16139451e-01 -1.65607601e-01
 -4.30847794e-01  3.09460700e-01  2.80855179e-01 -4.26417202e-01
  1.73830136e-03 -2.82107770e-01  1.82877164e-02 -6.37706220e-02
 -4.88196462e-01 -7.17721507e-02  8.39443505e-02  3.63586813e-01
 -2.93130547e-01  8.24001385e-04 -6.10457547e-02  1.56207666e-01
  3.90973479e-01 -1.84834197e-01 -7.34426901e-02 -5.98979294e-02
 -4.26818937e-01 -2.74078339e-01  1.34749785e-01 -6.73316643e-02
 -1.99668586e-01 -5.75812995e-01 -4.46738660e-01 -1.55027658e-01
  2.05926389e-01  3.87454629e-02 -1.82625353e-01 -1.47449076e-01
 -4.29568708e-01 -4.96102214e-01 -1.53704301e-01 -1.66332737e-01
 -3.69702011e-01  2.37300038e-01  2.66993612e-01 -1.92055911e-01
 -8.21273252e-02  3.26066613e-01 -2.00147063e-01  2.07688019e-01
  8.55685398e-02 -1.50776908e-01 -1.79169714e-01 -1.35722041e-01
  1.86401501e-01 -5.25203571e-02 -3.42787474e-01  2.29378175e-02
 -4.94439825e-02 -2.07433119e-01 -1.22873567e-01  6.72813654e-02
 -7.00148493e-02  2.10246220e-01 -6.59108087e-02  1.73554480e-01
  1.04997896e-01  1.42545834e-01 -5.13646901e-01 -6.85390830e-02
  5.15607297e-01  1.49554983e-01 -3.27803612e-01 -4.22696024e-01
  2.17222720e-01  3.18823874e-01  2.17453822e-01 -3.18838984e-01
 -4.25923884e-01 -8.11562985e-02  1.80363387e-01  8.65357518e-02
 -2.92853028e-01  2.24647835e-01 -1.99869245e-01 -5.60368877e-03
  6.83125407e-02 -5.22438213e-02  2.87373751e-01  1.08131863e-01
  3.85056853e-01 -2.48332899e-02 -2.18026638e-01 -4.05005589e-02
  1.57388479e-01 -1.83815673e-01  3.25813174e-01  2.32404023e-01
 -2.59708613e-01  1.46572134e-02 -5.32354057e-01  2.83828497e-01
 -3.43311489e-01  2.58795530e-01 -8.49889442e-02  2.29464859e-01
 -1.55097793e-03 -5.16450629e-02  2.37627655e-01  8.28187346e-01
 -8.39858223e-03 -2.97423184e-01  1.64025530e-01 -1.07735902e-01]

In [91]:
# Also auch hier jedes Wort mit 300 Dimensionen
len(pre_w2v_model['accept'])

300

In [92]:
similartoaccept = ourfirst_w2v_model.wv.most_similar('accept', topn=20)  # get other similar words
similartoaccept

[('regarding', 0.995293140411377),
 ('concede', 0.9952071905136108),
 ('relation', 0.9944636225700378),
 ('lower', 0.9943214058876038),
 ('concerning', 0.9942907094955444),
 ('least', 0.9942597150802612),
 ('set', 0.9938871264457703),
 ('concession', 0.9938251972198486),
 ('propose', 0.9937353134155273),
 ('go', 0.9934653043746948),
 ('ask', 0.993195652961731),
 ('condition', 0.9931527376174927),
 ('change', 0.992684006690979),
 ('afford', 0.9925779700279236),
 ('could', 0.9925184845924377),
 ('asked', 0.9924794435501099),
 ('make', 0.9924538731575012),
 ('extend', 0.9924453496932983),
 ('increase', 0.992306649684906),
 ('also', 0.9922778606414795)]

In [93]:
similartoreject = ourfirst_w2v_model.wv.most_similar('reject', topn=20)  # get other similar words
similartoreject

[('understanding', 0.9995661973953247),
 ('board', 0.9994473457336426),
 ('yes', 0.999391496181488),
 ('back', 0.9993482828140259),
 ('final', 0.9992919564247131),
 ('negotiations', 0.9992586374282837),
 ('cooperative', 0.9992192983627319),
 ('argumentation', 0.9991856813430786),
 ('youre', 0.9991768598556519),
 ('question', 0.9991662502288818),
 ('today', 0.9991151690483093),
 ('found', 0.9990727305412292),
 ('inform', 0.9990708231925964),
 ('successful', 0.9990637898445129),
 ('efforts', 0.9989858269691467),
 ('pandemic', 0.998969554901123),
 ('partner', 0.9989651441574097),
 ('considered', 0.998950719833374),
 ('joint', 0.9988986253738403),
 ('member', 0.9988948106765747)]

In [94]:
#Als Recap, das ist unser selbst traniertes Modell 
ourfirst_w2v_model.wv